sites:
  migri:
    base_url: "https://migri.fi"
    description: "Finnish Immigration Service website"
    crawler_config:
      max_depth: 2
      limit: 100
      render: true
      source: "all"

  te_palvelut:
    base_url: "https://toimistot.te-palvelut.fi"
    description: "TE Services (Work and Economic Development) website"
    crawler_config:
      max_depth: 2
      limit: 100
      render: true
      source: "all"

  kela:
    base_url: "https://www.kela.fi"
    description: "Kela (Social Insurance Institution of Finland) website"
    crawler_config:
      max_depth: 2
      limit: 100
      render: false
      source: "all"

  vero:
    base_url: "https://www.vero.fi/en/"
    description: "Vero (Guidance about taxation in Finland) website"
    crawler_config:
      max_depth: 2
      limit: 100
      render: false
      source: "all"

  dvv:
    base_url: "https://dvv.fi/"
    description: "DVV (Digital and population data services agency) website"
    crawler_config:
      max_depth: 2
      limit: 100
      render: false
      source: "all"